
* koma-biber-minimal-example

** Purpose of this project

This is a mininal [[http://en.wikipedia.org/wiki/LaTeX][LaTeX]] document testing [[http://www.komascript.de/][KOMA Script]] class with [[http://biblatex-biber.sourceforge.net/][biber]].


** Requirements

This example uses up-to-date technology like pdflatex, [[http://www.tex.ac.uk/tex-archive/info/translations/biblatex/de/][biblatex]]
(instead of BibTeX-Format), and [[http://en.wikipedia.org/wiki/Biber_(LaTeX)][biber]] (instead of
bibtex-compiler). You should be familiar with compiling LaTeX
documents by yourself. If you are new to LaTeX please get basic
knowledge from tutorial pages such as [[http://LaTeX.TUGraz.at][this one]].

** Why?

Unfortunately, biber is not that popular yet. This leads to software
version incompatibilities I faced multiple times with [[http://miktex.org/][MiKTeX]] or
MiKTeX portable.

To test these software packages, I use this minimal example here with:

#+begin_src sh
pdflatex bibtex-minimal-example
biber bibtex-minimal-example
pdflatex bibtex-minimal-example
pdflatex bibtex-minimal-example
#+end_src

If the software is working properly, you should get
[[file:bibtex-minimal-example.pdf][bibtex-minimal-example.pdf]] with correct citations. In order to
compare this PDF result to the way is should look like, I have added
the file [[file:expected-result.pdf][expected-result.pdf]].


** license

[[https://github.com/novoid/koma-biber-minimal-example][koma-biber-minimal-example]]
from https://github.com/novoid/koma-biber-minimal-example is licensed
under a 
[[http://creativecommons.org/licenses/by-sa/3.0/][Creative
Commons Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license]].

  
